repository: ${GITHUB_REPOSITORY}/runn
coverage:
  if: false
codeToTestRatio:
  if: false
testExecutionTime:
  if: false
diff:
  datastores:
    - local://
comment:
  if: is_pull_request
summary:
  if: true